core/urls.py
from django.urls import path

from . import views
from .views import Homepage

app_name = 'core'

urlpatterns = [
    path('', Homepage.as_view(), name='homepage'),
]

posts/urls.py
from django.urls import path

from .views import PostDetail, PostList

app_name = 'posts'

urlpatterns = [
    path('<category>/', PostList.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<slug:slug>/', PostDetail.as_view(), name='post_detail'),
]

rop/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('', include('core.urls', namespace='core')),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
# from django.db import models


# Really simple initially. Only putting this in place for future use.
class User(AbstractUser):

    def __str__(self):
        return self.first_name

categories/models.py
from django.db import models
from django.utils.text import slugify


class Category(models.Model):
    title = models.CharField(max_length=50,
                             help_text='Keep the category name short and descriptive.')
    slug = models.SlugField(max_length=60,
                            unique=True)
    parent = models.ForeignKey('self',
                               on_delete=models.SET_NULL,
                               blank=True,
                               null=True,
                               related_name='parent_category')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title

core/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.urls import reverse
from django.utils.html import mark_safe
from django.utils.text import slugify
from markdown import markdown

from categories.models import Category


class Post(models.Model):
    title = models.CharField(max_length=200,
                             help_text='Give your post a short, clear, title.')
    subtitle = models.CharField(max_length=220,
                                help_text='Type in a subtitle if the post will benefit from it.',
                                blank=True,
                                null=True)
    slug = models.SlugField(max_length=200,
                            unique_for_month='created')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category,
                                 on_delete=models.SET_NULL,
                                 blank=True,
                                 null=True,
                                 related_name='posts')
    summary = models.TextField(blank=True,
                               null=True)
    body = models.TextField()
    is_published = models.BooleanField()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def body_as_markdown(self):
        return mark_safe(markdown(self.body, safe_mode='escape'))

    def get_absolute_url(self):
        return reverse('posts:post_detail',
                       args=[self.created.year,
                             self.created.month,
                             self.slug])

    def __str__(self):
        return self.title

accounts/views.py
from django.shortcuts import render

# Create your views here.

categories/views.py
from django.shortcuts import render

# Create your views here.

core/views.py
# from django.shortcuts import render
from django.views.generic import ListView

from posts.models import Post


class Homepage(ListView):
    queryset = Post.objects.filter(is_published=True).order_by('-created')
    template_name = 'core/homepage.html'

posts/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView

from .models import Post
from categories.models import Category


class PostList(ListView):

    def get_queryset(self):
        self.category = get_object_or_404(Category, title=self.kwargs['category'])
        return Post.objects.filter(category=self.category).filter(is_published=True).order_by('-created')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        context['all_posts'] = Post.objects.all().filter(is_published=True).order_by('-created')
        return context


class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_posts'] = Post.objects.all().filter(is_published=True).order_by('-created')
        return context

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>{% block title %}Rite of Passage by Calum Andrew Morrell{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'core:homepage' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'posts:post_list' category='Commentary' %}">Commentary</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Tutorials</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'posts:post_list' category='Python' %}">Python</a>
                            <a class="dropdown-item" href="{% url 'posts:post_list' category='Django' %}">Django</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'posts:post_list' category='Bootstrap' %}">Bootstrap</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block hero %}{% include 'core/hero_full.html' %}{% endblock %}

    {% block content %}{% endblock %}

    <footer class="container">
        <hr>
        <div class="text-center">
            <p>All content copyright <strong>Calum Andrew Morrell</strong><br><em>(except where it isn't)</em></p>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

core/templates/base_blank.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Rite of Passage by Calum Andrew Morrell{% endblock %}</title>
</head>
<body>
    <h1>Rite of Passage</h1>
    <h2>A development and learning blog by Calum Andrew Morrell</h2>

    <a>Home</a>
    <a>Tutorials</a>
    <a>Bulma</a>
    <a>Django</a>
    <a>Python</a>
    <a>Blog posts</a>
    <a>Almost interesting stuff</a>

    {% block content %}{% endblock %}

    <footer>
        <div>
            <p>All content copyright <strong>Calum Andrew Morrell</strong></p>
        </div>
    </footer>
</body>
</html>

core/templates/core/hero_full.html
<div class="jumbotron">
    <div class="container">
        <h1 class="font-weight-bold">Rite of Passage</h1>
        <h4>A development and learning blog</h4>
        <h6 class="font-italic">by Calum Andrew Morrell</h6>
    </div>
</div>

core/templates/core/hero_minimal.html
<div class="jumbotron">
    <div class="container">
        <h1 class="font-weight-bold">Rite of Passage</h1>
        <h4>A development and learning blog</h4>
        <h6 class="font-italic">by Calum Andrew Morrell</h6>
    </div>
</div>

core/templates/core/homepage.html
{% extends 'base.html' %}

{% load humanize %}

{% block content %}
    <div class="container">
        <h3 class="text-center">The obligatory website introduction</h3>
        <br>
        <div class="row text-justify">
            <div class="col">
                <p>It's become a bit of a stereotype in web development circles to write a blog while learning how to use the languages and frameworks needed for a useful modern website.
                    I thought I might as well become another spec of dust in the vacuum of development. So ... what's the point?</p>
            </div>
            <div class="col">
                <p>It's basically to help learn the tools of the trade better.
                    Tutorials are helpful - sometimes - but it's difficult to really understand the tools and how to use them when you're following along with someone telling you what to do at each step.
                    It's so much faster to mistakes and learn how to fix them.</p>
            </div>
        </div>
        <hr>
    </div>
    <div class="container">
        <h3 class="text-center">Recent posts</h3>
        <br>
        <div class="card-deck text-center">
            {% for post in object_list|slice:':3' %}
                <div class="card">
                    <div class="card-header text-muted">
                        {{ post.category }}
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h5>
                        <p class="card-text">{% if post.summary %}{{ post.summary }}{% else %}{{ post.body | truncatechars:200 }}{% endif %}</p>
                    </div>
                    <div class="card-footer text-muted">
                        published {{ post.created | naturaltime }}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

core/templates/core/sidebar_default.html
{% if all_posts %}
    <div>
        <h5>All recent posts</h5>
        <ul class="list-unstyled">
        {% for post in all_posts|slice:':10' %}
            <li>
                <a href="{{ post.get_absolute_url }}">{{ post.title | truncatechars:30 }}</a>
                <br>
                <p class="text-muted">{{ post.category }}</p>
            </li>
        {% endfor %}
        </ul>
    </div>
{% endif %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <h4 class="font-weight-bold">{{ post.title }}</h4>
                {% if post.subtitle %}<h5>{{ post.subtitle }}</h5>{% endif %}
                <p class="font-italic">Originally written on the {{ post.created | date:'jS \o\f F, Y' }}
                {% if post.created.date != post.updated.date %}
                    and last updated on the {{ post.updated | date:'jS \o\f F, Y' }}
                {% endif %}
                </p>
                <div class="text-justify">
                    {{ post.body_as_markdown }}
                </div>
            </div>

            <div class="col-md-auto">
                {% include 'core/sidebar_default.html' %}
            </div>
        </div>
    </div>
{% endblock %}

posts/templates/posts/post_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                {% if object_list %}
                    <h3>Recent posts in the {{ category }} category</h3>
                    {% for post in object_list %}
                        <hr>
                        <a class="h4 font-weight-bold" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        {% if post.subtitle %}<h5>{{ post.subtitle }}</h5>{% endif %}
                        {% if post.summary %}
                            <p>{{ post.summary|linebreaksbr }}</p>
                        {% else %}
                            <p>{{ post.body_as_markdown | truncatechars:400 }}</p>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    <h3>Oh No!</h3>
                    <h5>I haven't written any tutorials for the {{ category }} category yet.</h5>
                    <p class="text-muted">(sorry not sorry)</p>
                {% endif %}
            </div>

            <div class="col-md-auto">
                {% include 'core/sidebar_default.html' %}
            </div>
        </div>
    </div>
{% endblock %}